services:
  lobo-liquibase:
    container_name: lobo-liquibase
    image: liquibase/liquibase:latest

    command: >
      update
      --changelog-file=changelog.xml
      --driver=org.postgresql.Driver
      --classpath=/liquibase/lib/postgresql.jar
      --username=postgres
      --password=postgres
      --url=jdbc:postgresql://host.docker.internal:5432/postgres

    volumes:
      - /var/lib/jenkins/workspace/aniket/config/changelog.xml:/liquibase/changelog.xml
      - /var/lib/jenkins/workspace/aniket/scripts:/liquibase/scripts
      - /var/lib/jenkins/workspace/aniket/postgresql-42.7.3.jar:/liquibase/lib/postgresql.jar

    extra_hosts:
      - "host.docker.internal:host-gateway"